import { ClerkProvider } from '@clerk/nextjs'
import { ThemeProvider } from "@/components/theme-provider"
import { Inter } from "next/font/google";
import { Toaster } from 'sonner'
import "./globals.css";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body>
        <ThemeProvider
            attribute="class"
            forcedTheme='dark'
            storageKey='gamehub-theme'
          >
            <Toaster theme="light" position='bottom-center' />
            {children}
          </ThemeProvider>
          </body>
      </html>
    </ClerkProvider>
  );
}
